### ISSUE TITLE
执行定时任务提示django.db.utils.DatabaseError

### ISSUE THREAD

**Issue by onepve** [ghosx/TiebaProject#12]
使用环境
centos6
Python 3.5.7
appnode搭建的mysql5.5
```
[root@ten_sh2 TiebaProject]# /usr/bin/python3 /home/TiebaProject/manage.py crontab run 2a0fd7e34f6c664c77eb33bfd85b6cb8
Traceback (most recent call last):
  File "/home/TiebaProject/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/python3/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/python3/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/python3/lib/python3.5/site-packages/django/core/management/base.py", line 301, in run_from_argv
    connections.close_all()
  File "/usr/local/python3/lib/python3.5/site-packages/django/db/utils.py", line 225, in close_all
    connection.close()
  File "/usr/local/python3/lib/python3.5/site-packages/django/db/backends/base/base.py", line 278, in close
    self.validate_thread_sharing()
  File "/usr/local/python3/lib/python3.5/site-packages/django/db/backends/base/base.py", line 531, in validate_thread_sharing
    % (self.alias, self._thread_ident, _thread.get_ident())
django.db.utils.DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id -1216698160 and this is thread id 3062651516.
```

**Comment by onepve** [comment]
app.log报错
```
2019-11-01 crontab.py[line:147] Failed to complete cronjob at ('*/1 * * * *', 'YunHui.cron.do', '>> do.log')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.5/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/home/TiebaProject/YunHui/cron.py", line 339, in do
    content = getContent()
  File "/home/TiebaProject/YunHui/cron.py", line 56, in getContent
    cursor.execute(sql)
  File "/usr/local/python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tieba.YunHui_content' doesn't exist")
```

**Comment by ghosx** [comment]
没有创建这个表 `YunHui_content`
