### ISSUE TITLE
我这边部署出了一些问题。

### ISSUE THREAD

**Issue by 955s** [ghosx/TiebaProject#4]
root@mayqueen:/usr/sju/TiebaProject# python3 manage.py runserver 0.0.0.0:8008
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 04, 2019 - 19:18:44
Django version 2.2, using settings 'TiebaProject.settings'
Starting development server at http://0.0.0.0:8008/
Quit the server with CONTROL-C.
[04/Apr/2019 19:19:05] "GET / HTTP/1.1" 200 4794
Not Found: /favicon.ico
[04/Apr/2019 19:19:06] "GET /favicon.ico HTTP/1.1" 404 4008
[04/Apr/2019 19:19:24] "GET /login/ HTTP/1.1" 200 2388
[04/Apr/2019 19:19:27] "GET / HTTP/1.1" 200 4794
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view YunHui.views.index didn't return an HttpResponse object. It returned None instead.
[04/Apr/2019 19:20:04] "POST / HTTP/1.1" 500 53542
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view YunHui.views.index didn't return an HttpResponse object. It returned None instead.
[04/Apr/2019 19:20:52] "POST / HTTP/1.1" 500 53542
[04/Apr/2019 19:25:07] "GET / HTTP/1.1" 200 4794

**Comment by ghosx** [comment]
收到
